### ISSUE TITLE
It was labeled Java.Lang.ExceptionInInitializerError: null.

### ISSUE THREAD

**Issue by tatsuki123321** [ArtixAllMighty/Paintings--#53]
[crash-2021-08-31_20.36.18-fml.txt](https://github.com/ArtixAllMighty/Paintings--/files/7083557/crash-2021-08-31_20.36.18-fml.txt)

**Comment by AbsolemJackdaw** [comment]
Caused by 1: java.lang.IllegalArgumentException: Illegal character in path at index 103: file:/D:/Users/E/AppData/Roaming/.minecraft/versions/1.17.1mod/./resourcepacks/Halcyon%20Days%20v1.2%20[1.6-1.7].zip

check your painting pack for illegal characters. 
accepteed cahracters are 

all a to z letters, lower case
all 0 to 9 letters
. - / _

aka

[a-z0-9/._-]

**Comment by AbsolemJackdaw** [comment]
Due to lack of response, the answer above is now marked as the solution.
