### ISSUE TITLE
Crash on version 1.9.0 Fabric

### ISSUE THREAD

**Issue by Skeithh** [ArtixAllMighty/Paintings--#56]
Unsure what the issue is, I tried deleting all my configs in the configs folder to refresh them (after seeing that having been a potential solution in an earlier crash that was solved), no dice.

crash report attached
[crash-2022-01-14_18.59.20-client.txt](https://github.com/ArtixAllMighty/Paintings--/files/7872339/crash-2022-01-14_18.59.20-client.txt)

**Dependency Versions:**
Fabric 0.12.12
Fabric API 0.46.0
Cloth config 6.1.48

**Comment by strikerrocker** [comment]
Is this a new world or a old one. If old one can you upload the world file so we can look into it.

**Comment by AbsolemJackdaw** [comment]
are you using any other resource and/or painting packs by any chance ? 

on first look, it seems the game is trying to register the same painting twice

``Caused by: java.lang.RuntimeException: Attempted to register ID ResourceKey[minecraft:motive / paintings:cat] at different raw IDs (40, 101)! If you're trying to override an item, use .set(), not .register()!
``

**Comment by AbsolemJackdaw** [comment]
(accidentally closed sorry) 
Striker : i do not think this is an old world issue. the registry is void of added paintings on restart and gets populated with modded paintings when launching the game

If it is related to the registry of the paintings , your regular game log (latest.log, found in the log folder in your isntall directory) should have all the details on what packs try to register a 'cat' painting

**Comment by Skeithh** [comment]
I'm only using one resource pack in which the ones I made for the paintings mod are in, and in there there is indeed a cat painting. I wouldn't be sure... How the issue started because of it but here's the pack so you can test.
[wovenpack.zip](https://github.com/ArtixAllMighty/Paintings--/files/7872596/wovenpack.zip)

This crash doesn't occur upon world load, but upon game launch.

I tried renaming the 'cat' painting to 'kittycat' and it still continued crashing as if it were trying to load 'cat'

**Comment by AbsolemJackdaw** [comment]
thats because there's a cache of painting json files located in the painting folder in your installation directory. 
if you only renamed the file in your json inside the pack, it will not apply the changes to the cache.

deleting the painting folder will recopy all json files from out of the resourcepacks, including changes

**Comment by AbsolemJackdaw** [comment]
![image](https://user-images.githubusercontent.com/3628535/149571463-731ca936-dce6-4ae8-904a-685acfed894b.png)

paintings++ does indeed also include a cat painting. 
i'll see if i can rename it to a more unique name, but the best quickfix is going to be you deleting cache and editing your painting pack's json file (and texture name) to reference another name.

**Comment by Skeithh** [comment]
renamed it to kittycat for now and refreshed the paintings directory, works fine now. Thanks for the quick troubleshooting :>

I personally would recommend just giving each of the default paintings the prefix 'paintings_'

**Comment by AbsolemJackdaw** [comment]
i will do so for the futur probably. will break worlds tough. 
I should include in my tutorial that people could prefix their paintings with their name too. 

Definitly will have to update the simple names in the integrated painting json though
